# http://www.appveyor.com/docs/appveyor-yml
# mostly copied from nan appveyor.yml
os: Visual Studio 2017

environment:
  matrix:
    - electron_version: 1.8.4
    - electron_version: 4.0.1

platform:
  - x86

# git clone depth
clone_depth: 5

# Install scripts. (runs after repo cloning)
install:
  - ps: Install-Product node 8.10.0
  - npm install

build_script:
  - npm install %lib% --runtime=electron --target=%electron_version% --disturl=https://atom.io/download/atom-shell --save
  - cd node_modules/%lib%/ && npm run pregyp package


deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: NLYzbwHiP2gxxQ0p+Wb0sJphYmLcYVNOS/BbB0aZwFZTJiahe2mEQeqT/Rp+qEVZ
  artifact: /node_modules/node-libcurl/build/stage/.*\.gz/
  draft: true
  prerelease: false
  on:
    branch: master                
    APPVEYOR_REPO_TAG: true 

# Set build version format here instead of in the admin panel.
version: "{build}"
